# Generated by Django 2.2.1 on 2019-05-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='tanggal_lahir',
        ),
    ]
