# Generated by Django 2.2.1 on 2019-05-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_mahasiswa_tanggal_lahir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='jenis_kelamin',
            new_name='gender',
        ),
    ]
